dnsmasq:
  customDnsEntries:
    - address=/pihole.home.io/10.0.0.101
    - address=/postgres.home.io/10.0.0.102


persistentVolumeClaim:
  enabled: true

serviceWeb:
  loadBalancerIP: 10.0.0.101
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 10.0.0.101
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

